# Generated by Django 5.2 on 2025-04-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.CharField(default='', max_length=250),
        ),
    ]
